version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "src/server"
    # Check for updates once a week
    schedule:
      interval: "weekly"
