version: '3'

services:
  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    env_file:
      - server/messaging/kafka-variables.env
    depends_on:
      - zookeeper
    expose:
      - "9092"  
    ports:
      - '9092:9092'
  server:
    container_name: server
    build: './server'
    depends_on:
      - kafka
    ports: 
      - 8080:8080
    restart: 
      "on-failure"